
name: dtc_analytics
version: '1.0.0'
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dtc_analytics:
    intermediate:
      microsoft:
        +enabled: false
      amazon_sc:
        +enabled: false
    marts:
      dtc:
        kpi-daily:
          channel:
            dtc_joined__kpi_daily_microsoft_channel:
              +enabled: false
        kpi-monthly-to-date:
          channel:
            dtc_joined__kpi_monthly_to_date_microsoft_channel:
              +enabled: false
    staging:
      microsoft:
        +enabled: false
      amazon_sc:
        +enabled: false
