with

shopify_orders as (

    select
        
        id,
        name,
        (customer ->> 'id')::bigint as customer_id,
        note,
        tags,
        test,
        lower(email) as email,
        phone,
        token,
        app_id,
        number,
        refunds,
        "user_id",
        customer,
        closed_at,
        tax_lines,
        total_tax,
        created_at,
        deleted_at,
        line_items,
        tax_exempt,
        updated_at,
        source_name,
        total_price,
        cancelled_at,
        fulfillments,
        order_number,
        processed_at,
        total_weight,
        lower(cancel_reason) as cancel_reason,
        lower(contact_email) as contact_email,
        total_tax_set,
        checkout_token,
        discount_codes,
        referring_site,
        shipping_lines,
        subtotal_price,
        taxes_included,
        billing_address,
        estimated_taxes,
        note_attributes,
        total_discounts,
        total_price_set,
        total_price_usd,
        lower(financial_status) as financial_status,
        order_status_url,
        shipping_address,
        current_total_tax,
        total_outstanding,
        lower(fulfillment_status) as fulfillment_status,
        subtotal_price_set,
        total_tip_received,
        confirmation_number,
        current_total_price,
        total_discounts_set,
        discount_allocations,
        current_total_tax_set,
        discount_applications,
        payment_gateway_names,
        current_subtotal_price,
        total_line_items_price,
        buyer_accepts_marketing,
        current_total_discounts,
        current_total_price_set,
        total_shipping_price_set,
        current_subtotal_price_set,
        total_line_items_price_set,
        current_total_discounts_set,
        current_total_additional_fees_set,
        original_total_additional_fees_set,

        -- _airbyte_shopify_orders_hashid,
        -- _airbyte_unique_key,
        _airbyte_raw_id,
        _airbyte_extracted_at,
        _airbyte_meta,

        created_at at time zone 'america/los_angeles' as created_at_pt,
        updated_at at time zone 'america/los_angeles' as updated_at_pt,
        cancelled_at at time zone 'america/los_angeles' as cancelled_at_pt

    from {{ source('shopify', 'shopify_v2_orders') }}

)

select * from shopify_orders