version: 2

models:
  - name: dtc_joined__kpi_daily_all_channels
    columns:
      - name: report_date
        tests:
          - not_null
          - unique
  - name: dtc_joined__kpi_daily_facebook_channel
    columns:
      - name: report_date
        tests:
          - not_null
          - unique
  - name: dtc_joined__kpi_daily_google_channel
    columns:
      - name: report_date
        tests:
          - not_null
          - unique
  - name: dtc_joined__kpi_daily_influencers_channel
    columns:
      - name: report_date
        tests:
          - not_null
          - unique
  - name: dtc_joined__kpi_daily_microsoft_channel
    columns:
      - name: report_date
        tests:
          - not_null
          - unique
  - name: dtc_joined__kpi_daily_other_channel
    columns:
      - name: report_date
        tests:
          - not_null
          - unique
  - name: dtc_joined__kpi_daily_post_pilot_channel
    columns:
      - name: report_date
        tests:
          - not_null
          - unique
  - name: dtc_joined__kpi_daily_tiktok_channel
    columns:
      - name: report_date
        tests:
          - not_null
          - unique
  